### ISSUE TITLE
Windows 10 missing drivers during install, possibly because of MBR + UEFI instead of GPT

### ISSUE THREAD

**Issue by Sporif** [jsamr/bootiso#15] opened 2018-07-12 13:38 UTC
I think a GPT option is needed for Windows 10 ISOs.  Currently mbr+rsync is used, but this causes some kind of weird missing driver error in the installation setup. I tried [windows2usb](https://github.com/ValdikSS/windows2usb) with mbr and it showed the same issue, but with gpt it worked.

**Comment by jsamr** [comment] 2018-07-12 14:14
@Sporif Thanks for the report, I'll check this up.

**Comment by jsamr** [comment] 2018-07-14 15:37
@Sporif I have reports of other users for which Windows10 boot worked great. Can you provide more details on the steps you went through ? Would you have screenshots or error codes Windows10 installer gave about missing drivers? Or any reliable source confirming this issue with MBR + UEFI?

Thanks a lot for your help.

**Comment by Sporif** [comment] 2018-07-14 16:22
All I did was:

    bootiso <path-to-Win10_Edu_1803_English_x64.iso>

It goes through mbr+rsync successfully, nothing seems amiss, but this is the error I get upon clicking 'install now' after booting the usb:

https://cdn.windowsreport.com/wp-content/uploads/2018/04/a-media-driver-is-missing-windows-10--720x480.jpg

It shows up with the default bios settings (CSM enabled) and my custom settings with CSM disabled. Only the UEFI option works, the other option that appears when CSM is enabled can't even boot the usb.

I tried using mbr+ntfs on Rufus and there was no issue. So maybe the fat32 partition is the problem? Or it could just be this education iso.

I'll try investigating some more, but I personally think a GPT option would be nice regardless.

**Comment by jsamr** [comment] 2018-07-14 16:31
@Sporif
Thanks. I will add a feature request for GPT and wait to see if it gets upvoated. There is some work to do and I'd rather support more important features first. But if it's really causing driver issues in W10 I might reconsider my priorities.

So we need to isolate potential causes here. I suggest :
- checksum the ISO
- try bootiso with `--mrsync -t ntfs` options on the same ISO

**Comment by Sporif** [comment] 2018-07-14 16:55
Well this is quite strange, the issue seems to have fixed itself. Did the exact same actions and no error popped up.

**Comment by jsamr** [comment] 2018-07-14 18:29
You can confirm not using `-t ntfs` ?

**Comment by Sporif** [comment] 2018-07-14 18:31
Yep, did it with only path like before. So mbr+fat32+rsync was used.

**Comment by jsamr** [comment] 2018-07-14 22:50
@Sporif OK I'll close then.

**Comment by HassanMirza01** [comment] 2018-07-25 15:17
This issue came due to MBR booting on a GPT Partitioned HDD, or UEFI selected bios, we can't do it like vice virsa, GPT burned stuff should applied on GPT and mbr on mbr style....

**Comment by jsamr** [comment] 2018-07-25 15:26
@HassanMirza01 I don't think this is right. UEFI boot should be independent of partition table scheme, see for example [this extract from Manjaro wiki](https://wiki.manjaro.org/index.php?title=Some_basics_of_MBR_v/s_GPT_and_BIOS_v/s_UEFI#BIOS_vs._UEFI):
> Though UEFI supports the traditional master boot record (MBR) method of hard drive partitioning, it doesn't stop there. It's also capable of working with the GUID Partition Table (GPT), which is free of the limitations the MBR places on the number and size of partitions.

[Wikipedia](https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface) also has an entry on this:
> In addition to the standard PC disk partition scheme that uses a master boot record (MBR), UEFI also works with a new partitioning scheme called GUID Partition Table (GPT), which is free from many of the limitations of MBR

And I have never come across any issue with UEFI + MBR + Linux. However Windows might be more restrictive on UEFI, and if it is, GPT should be supported by `bootiso`.

**Comment by HassanMirza01** [comment] 2018-07-25 15:30
as i told before, for me any Linux distro is booting fine with both GPT and MBR, both with DD and rsync methods, Linux distros dont give any issue, Windows ISO are pain in ass, they need special treatment, you can never ever boot GPT booted on MBR scheme and MBR booted on GPT scheme atleast for windows, i have experience of it many times, all my issues solved now as i can make gpt too now, adding in my script, removing all syslinux stuff too, as i got another easy idea of getting it with grub install, ;)

**Comment by jsamr** [comment] 2019-01-30 07:52
I am ~~considering~~  planning a `--gpt` flag in next release, see #19

Seen repro [here](https://www.linuxuprising.com/2018/07/bootiso-easy-iso-to-bootable-usb-drive.html): 
![image](https://user-images.githubusercontent.com/3646758/51966225-3a9dd180-246c-11e9-8a2c-934dbd1fc4b4.png)

**Comment by HassanMirza01** [comment] 2019-01-30 10:35
i have it working fine here in my script... i will do a merge request for you soon ;)

**Comment by jsamr** [comment] 2019-01-30 11:08
@HassanMirza01 Thanks! You can propose PRs on branch `next`

**Comment by MichaelFirsov** [comment] 2019-10-22 15:02
Confirm - that's the really strange issue and as far as I know it has nothing to do with MBR/UEFI and etc. Here are my tests:

1) In _Windows 7 USB DVD Download tool_ I create a bootable usb (**Transcend usb3 8GB**) using the en_windows_10_consumer_editions_version_1909_x64_dvd_be09950e.iso - error

2) In _Windows 7 USB DVD Download tool_ I create a bootable usb (**Transcend usb3 8GB**) using the en_windows_10_business_edition_version_1809_updated_sept_2018_x64_dvd_f0b7dc68.iso - error

3) In _Windows 7 USB DVD Download tool_ I create a bootable usb (**Transcend usb3 8GB**) using the ru_windows_10_business_edition_version_1809_updated_sept_2018_x86_dvd_e75f8430.iso - error

4)  In _Windows 7 USB DVD Download tool_ I create a bootable usb (**Transcend usb3 8GB**) using the en_**windows_7**_professional_with_sp1_x64_dvd_u_676939.iso - success

--------------------------------------------------------------------------------------------------
5)  ... In _Windows 7 USB DVD Download tool_ I create a bootable usb using any of the aforementioned images onto ANOTHER **Transcend usb3 8GB** stick - exactly the same as the first one (these two usb sticks have been purchased at the same time) - works perfect!

**Comment by jsamr** [comment] 2019-10-31 10:37
@MichaelFirsov Thank you for this thorough report. It's very hard to diagnose such heisenbugs! I have a feeling it might be related to #48, in a different way. There might be a race condition somewhere that involves i/o operations with a tool used by bootiso. Because it is hard to diagnose, I need to wait for more feedback. Your was definitely helpful, thanks.

**Comment by MichaelFirsov** [comment] 2019-10-31 13:53
jsamt, thank you for your reply!

**Comment by jsamr** [comment] 2020-04-29 19:47
I believe now it was related to #48. Fixed in the next branch.
4.0.0 release is coming out soon.

**Closed as completed** 2020-04-29 19:51 UTC
Labels: bug, installation-process

**Comment by jsamr** [comment] 2020-05-09 18:08
Also, GPT will be default partition table scheme when UEFI support is detected in mount+rsync mode.

**Comment by jsamr** [comment] 2020-05-11 19:52
I could reproduce the failure with v3 which was not caused by GPT, but a `sync` call missed in background. I am now certain this bug and #48 are related, and I can confirm this issue has been fixed in the upcoming v4!
